### PR TITLE
Hello word in lingala

### PR DESCRIPTION
**Pull request by donmbelembe**
6279a5ae4f1eec18a46671992eaaa6680ffb26c556a3ebf10112bd4d3d5bc131

Lingala (Ngala) (Lingala: lingála) is a Bantu language spoken throughout the northwestern part of the Democratic Republic of the Congo and a large part of the Republic of the Congo. It is spoken to a lesser degree in Angola, the Central African Republic and Southwest & Southcentral Republic of South Sudan. There are over 40 million lingalophones.

https://en.wikipedia.org/wiki/Lingala

### CODE REVIEW

**Comment by Niekon01** [comment]
ISO: correct
Translation: I am seeing "Mbote and binoculars" this in Google Translate. Can you confirm that this means Hello World in your language?
Review Required
@angle943

**Comment by donmbelembe** [comment]
Google is not able to translate into Lingala yet, the exact translation of **Hello word** is **Mbote Mokili** which is also fine,
**Mbote na bino** means **Hello everyone** which I think makes more sense, but **Mbote Mokili** is the correct translation, let me update my PR

**Comment by thesanjeevsharma** [comment]
@odetolataiwo I have paid this earlier. Don't send coins. Can you make sure this is logged into the system?

**Comment by odetolataiwo** [comment]
> @odetolataiwo I have paid this earlier. Don't send coins. Can you make sure this is logged into the system?

done

**Pull request merged**
