### PR TITLE
Adding Hello World in Tagalog | Filipino

### PR DESCRIPTION
**Pull request by wilsongayo**
e639afaaa92ea2372fde3f20e998eb9b1f76d0d2e5d6a54a10dc31b3e7fb9376

### CODE REVIEW

**Comment by wilsongayo** [comment]
#351

**Comment by Niekon01** [comment]
ISO: correct
Translation: correct
**Approved**

**Comment by wilsongayo** [comment]
> ISO: correct
> Translation: correct
> **Approved**

Thank you for the approval!

**Comment by thesanjeevsharma** [comment]
@odetolataiwo I have paid this earlier. Don't send coins. Can you make sure this is logged into the system?

**Comment by odetolataiwo** [comment]
done

**Pull request merged**
