### PR TITLE
Add a minimum node version for Website

### PR DESCRIPTION
**Pull request by denistsoi**
Resolves: https://github.com/thenewboston-developers/Website/issues/1396

### CODE REVIEW

**Comment by denistsoi** [comment]
@angle943 - perhaps we can bump the github actions to support node 14 instead?

**Comment by angle943** [comment]
can we do >12 for now? Unless you have a good reason for requiring 14+?

**Comment by denistsoi** [comment]
Sure I can do >12 but thought starting with current LTS might be a good baseline.

**Comment by angle943** [comment]
let's do 12 for now. We can discuss in the future about upping the requirements

**Comment by denistsoi** [comment]
changed to 12

**Pull request merged**
