### PR TITLE
[#743] Add new front end contributor

### LINKED ISSUE #743: New Contributor
Team: [TEAM NAME]

{
  "title": Software Developer
  "isLead":false
  "payPerDay": 2800,
  "createdDate": "2020-11-12
    "contributorId":
    "displayName": Meharban Singh
    "githubUsername": Meharban-Singh
    "profileImage": https://avatars1.githubusercontent.com/u/33323725?s=460&u=da67fec9d0eacc6f5680c789265fb372a75d71c0&v=4
    "slackUsername": Meharban Singh

### PR DESCRIPTION
**Pull request by jamessspanggg**
Fixes #743 

Acc No: c54c04774efaae20746fd3f29cdd619fea512e119bc1082b863572b2e8844104

### CODE REVIEW

**Comment by manishram** [comment]
**"createdDate": "2020-11-12T02:14:59.307535Z"** pushing new contributors to the **top of the list**.
**"createdDate": "2020-07-08T02:14:59.307535Z"** seems to work for now.

new-contributor-issue

**Comment by jamessspanggg** [comment]
I followed the `createdDate` specified in the original issue: 
> "createdDate": "2020-11-12"

Should I change the date to `2020-07-08` instead?

**Comment by jamessspanggg** [comment]
Seems like when the filter is `all`, the contributors are sorted based on `created_date`. Whereas for other filters, the contributors are sorted based on `created_date` while ensuring the team leads are in front of everyone else.

**Comment by manishram** [comment]
> I followed the `createdDate` specified in the original issue:
> 
> > "createdDate": "2020-11-12"
> 
> Should I change the date to `2020-07-08` instead?

I guess so. But wait for the **reviewer** if there's any better solution without losing correct data. But what I saw in the current **teams.json** file is that all members got "createdDate":"createdDate": "2020-07-08T02:14:59.307535Z" and few got "createdDate": "2020-05-09T02:14:59.307535Z". People who got later one had got their position misplaced and not sorted according to their `contributorId`.

**Review by amarjeet987 — CHANGES_REQUESTED** [review]
Related to https://github.com/thenewboston-developers/Website/issues/747

It'd probably be better to fix the sorting issue with the contributorId once and for all rather than hard coding the date into it by changing it's value, do let me know if you need any help with it.

**Comment by jamessspanggg** [comment]
> It'd probably be better to fix the sorting issue with the contributorId once and for all rather than hard coding the date into it by changing it's value, do let me know if you need any help with it.

Noted on this, should I change the `created_date` according to the issue, i.e. `2020-11-12` or following the rest of the `created_date`, i.e. `2020-07-08`?

**Comment by amarjeet987** [comment]
Keep the createdDate as suggested in the requirements for the issue. Once the sorting issue as per the contributor ID is resolved, it'd be fixed automatically anyway.

**Comment by jamessspanggg** [comment]
> Keep the createdDate as suggested in the requirements for the issue. Once the sorting issue as per the contributor ID is resolved, it'd be fixed automatically anyway.

noted on this. I observe that there are several PRs that were merged/pending that's with the incorrect date:
https://github.com/thenewboston-developers/Website/pull/755
https://github.com/thenewboston-developers/Website/pull/777
https://github.com/thenewboston-developers/Website/pull/746/files

**Comment by jamessspanggg** [comment]
@amarjeet987 it seems like the front end is sorting the teammembers in terms of the created_date instead of the contributorId. Should I create a PR in changing the sort order to be based on contributorId?

**Comment by amarjeet987** [comment]
I requested some changes in the contributionID issues assigned to @manishram already ( https://github.com/thenewboston-developers/Website/pull/746/files ). It's just that changing the date is first of mutating the static data, and isn't a long term solution anyway.

**Comment by amarjeet987** [comment]
> @amarjeet987 it seems like the front end is sorting the teammembers in terms of the created_date instead of the contributorId. Should I create a PR in changing the sort order to be based on contributorId?

You can comment on the issue #747 for it, and if it's assigned to you by a team lead, you can continue with it.

**Pull request merged**
