### PR TITLE
Kotlin developer Added

### PR DESCRIPTION
**Pull request by hasham56**
Fixed: #877 

Account Number: b5e439050e077544a563c08fbabc7c2729ad906cb0d7d68b89501c35f4b878aa

### CODE REVIEW

**Comment by Hristijan95** [comment]
contributorId should not be null, it should be +1 from the latest contributor(51).
Also, the `isLead` field is incorrect.

**Comment by hasham56** [comment]
@Hristijan95 Sir what if someone else do 52 for contributorId before me? what i did here is i added 52 for #878 and 53 for #877 ... is it ok? or should i recreate merge request?

**Comment by Hristijan95** [comment]
If there is a conflict in some situation, I'll fix it before merging.

**Comment by hasham56** [comment]
@Hristijan95 thanks ❤️ someone did fixed contributors id before merging my PR 😅

**Pull request closed without merging**
