### PR TITLE
hello world in turkish (#351)

### PR DESCRIPTION
**Pull request by xZliman**
dad0bec19e39f755440a295a24095633c7b1f18e104655b12b34ff945345f4c6

### CODE REVIEW

**Comment by xZliman** [comment]
#351

**Review by thesanjeevsharma — APPROVED** [review]

**Comment by thesanjeevsharma** [comment]
@xZliman Thank you for your contribution.

**Comment by Niekon01** [comment]
ISO: correct
Translation: correct
**Approved**

@angle943 
Hey @xZliman thanks a lot for your contribution, however, I see this is your second PR for the same issue, first one being #518. It is best if you submit one language and that too, the one you speak natively so that others have a chance to contribute as well. Thank you.

**Comment by xZliman** [comment]
@Niekon01 Okay, my bad. Thank you!

**Comment by thesanjeevsharma** [comment]
@odetolataiwo I have paid this earlier. Don't send coins. Can you make sure this is logged into the system?

**Comment by odetolataiwo** [comment]
done

**Pull request merged**
