### PR TITLE
#581 - Fix no margin issue

### LINKED ISSUE #581: [Design] No Margin between Task Left Menu
There is no gap between 2 tabs of Task Left Menu. ( Chrome )
Makes them look smudged if the current tab and next tab are the 2 consecutive tabs.

margin

Giving 2px margin-bottom to [ .FlatNavLinks__option ] makes it look better:

margin1

Account Number: cd2400e0402fd081b2f71d08a9334e56d876eb589e096b6a0b8a6e4ac20a73c3

### PR DESCRIPTION
**Pull request by whitelionx**
Resolves #581 

Account number: fb84a32a698a03dd327c4ce673f19fa0acf6e68cb50f143d5d7c080471bc4625

Added a bottom margin for the flat nav links

### CODE REVIEW

**Review by thesanjeevsharma — CHANGES_REQUESTED** [review]
@whitelionx It should go in alphabetical order and make it 4px.

**Comment by whitelionx** [comment]
Changed it @thesanjeevsharma :D

**Review by thesanjeevsharma — APPROVED** [review]

**Comment by thesanjeevsharma** [comment]
@odetolataiwo I have paid this earlier. Don't send coins. Can you make sure this is logged into the system?

**Comment by odetolataiwo** [comment]
> @odetolataiwo I have paid this earlier. Don't send coins. Can you make sure this is logged into the system?

done

**Pull request merged**
