### PR TITLE
Hello world

### PR DESCRIPTION
**Pull request by velibor7**
Added hello world in Serbian

### CODE REVIEW

**Comment by shahraizali** [comment]
ISO Incorrect ❌  (Source: https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)
Spellings Incorrect (Google translator detect it as Slovak and making it Serbian translates to "
Hello Saint") ❌ 
Require Changes

**Comment by angle943** [comment]
@velibor7 please update the ISO code, and put it in the alphabetical order please. Also, can you verify what you wrote is correct?

**Comment by velibor7** [comment]
Updated the ISO code, put in alphabetical order, and yes, I can confirm that what I wrote is correct :)

**Comment by velibor7** [comment]
Updated ISO, put it in alphabetical order and yes I can confirm that what I wrote is correct :)

**Comment by Niekon01** [comment]
ISO: correct
Translation: correct
Approved

**Pull request merged**
