### PR TITLE
Added Afrikaans language

### PR DESCRIPTION
**Pull request by MirkoHotsHot**
Added 'Hello World' in Afrikaans language:

my account number: 802f34851bdfa1572f11fc4e58e44be3c01e92399bc4ba8d81e98b02254a0106

### CODE REVIEW

**Comment by Hristijan95** [comment]
@MirkoHotsHot , why did you remove the av language?

**Comment by MirkoHotsHot** [comment]
> 
> 
> @MirkoHotsHot , why did you remove the av language?

It was by an accident, sorry I placed it back

**Comment by Hristijan95** [comment]
@MirkoHotsHot , please fix the order as well, meaning av should be below ar - as it was before, otherwise ES lint is showing errors.

**Comment by MirkoHotsHot** [comment]
> 
> 
> @MirkoHotsHot , please fix the order as well, meaning av should be below ar - as it was before, otherwise ES lint is showing errors.

Is everything good now?

**Comment by Hristijan95** [comment]
@odetolataiwo @Rajputusman , 500.

**Pull request merged**
