### PR TITLE
#211 - site now working Possible fix for related issues: (#536, #534, #249) 

### PR DESCRIPTION
**Pull request by zinoadidi**
The fix is tested on IE but the solution should apply across most browsers that are lacking behind on the latest JS API updates.

Account number 
e6877a1a3f9bfbe313c7d2022675c6cf409fcf4eb425793acec4f2d69cb86fcb

### CODE REVIEW

**Comment by itsnikhil** [comment]
Hey,
I have already catered this issue #211 via https://github.com/thenewboston-developers/Website/pull/281 which was closed.
Sadly polyfills alone is not enough, css variable has been used all over the place along with SVG elements.
It was came to a conclusion to drop IE support.

**Comment by zinoadidi** [comment]
cool. i guess we could at least show a message that it's not supported; right now its blank without a polyfill
With polyfill it works in some of the latest version at least;

**Comment by itsnikhil** [comment]
Showing a message that IE is not supported would be better than a blank white page or a half baked broken page. 
Take approval from design team about this before you work on it

**Comment by zinoadidi** [comment]
SO need to know who is on the design team that can give input about this so I can carry on with the task

**Comment by itsnikhil** [comment]
@thesanjeevsharma @kristykjlee Can you please look into this

**Comment by Hristijan95** [comment]
Let's just set a message that IE is not supported at the moment. I'll close this issue.

**Pull request closed without merging**
