### PR TITLE
Add onClick function for Link in FaqDropDownCard | Fixes #1848

### LINKED ISSUE #1848: FAQ Question Link toggle issue
**Bug Description**
Clicking on any of the FAQ questions for the second time doesn't toggle off the answer dropdown.
This happens in both the FAQ page as well as those that are in the Home page.

**Steps to Reproduce**
1. Go to FAQ Section
2. Click on any of the questions and see that the answer drop-down is toggled.
3. Click the question again.
4. The answer drop-down is not toggled off.

**Expected behavior**
When we click the question for the second time, the user expects to toggle off the answer dropdown.

**Actual behavior**
When we click the question for the second time, the answer drop-down is not toggled off - rather, the answer is still displayed.

**OS and Browser**
 - OS: Arch Linux
 - Browser: Brave

### PR DESCRIPTION
**Pull request by hemanth-kotagiri**
This PR fixes the issue that I have raised regarding the FAQ Question toggle issue. Now, the link is clickable, and also the drop-down is togglable by clicking both on the Link as well as on the icon to the right.

Please lemme know if there are any issues.

### CODE REVIEW

**Review by jamessspanggg — APPROVED** [review]

**Comment by jamessspanggg** [comment]
@hemanth-kotagiri please provide your account number so that we can send you the bounty

**Comment by hemanth-kotagiri** [comment]
@jamessspanggg, here's my account number: 5468b09948f1be8034e043fffcc7a9ac915957b0877eed0eda7e88c3c3631351

**Comment by hemanth-kotagiri** [comment]
Hey @jamessspanggg . I have just checked my account balance, looks like the bounty hasn't yet been credited. Could you check that out, please?

**Comment by jamessspanggg** [comment]
@angle943 can you proceed with the payments for this PR?

**Pull request merged**
