### PR TITLE
Updated Clean and Crawl Post Request docs

### PR DESCRIPTION
**Pull request by tomijaga**
Resolves: #1637

I've tested this on [thenewboston-js](https://github.com/thenewboston-developers/thenewboston-js/pull/91) repo

### CODE REVIEW

**Comment by Rajputusman** [comment]
**QA Passed**

**Comment by jamessspanggg** [comment]
@tomijaga please revert the changes for `package-lock.json`

**Review by jamessspanggg — APPROVED** [review]

**Comment by angle943** [comment]
@tomijaga what is your account #?

**Comment by tomijaga** [comment]
@angle943 
It's 
8de30226230c35bbc1ce4a63c62a7b9c86bf0ce21fc7bc1a984b7884a9f88782

**Pull request merged**
