### PR TITLE
Add Romanian, Fix missing space.

### PR DESCRIPTION
**Pull request by ionutzaharia**
Hope it helps :)

### CODE REVIEW

**Comment by thesanjeevsharma** [comment]
@ionutzaharia Thank you for your contributuon! Can you tell me your account number so I can send you coins for this?

**Comment by ionutzaharia** [comment]
@thesanjeevsharma 37f45e2eec79ff2cff9460d980b048e97e54a256831427ee8f8a6f257cbd007e thanks!

**Comment by Rajputusman** [comment]
> @thesanjeevsharma 37f45e2eec79ff2cff9460d980b048e97e54a256831427ee8f8a6f257cbd007e thanks!

The account number is incorrect @ionutzaharia

**Comment by ionutzaharia** [comment]
@Rajputusman this is the account number, do I have to create a new one?
tnb

**Comment by Rajputusman** [comment]
Space was interfering

**Pull request merged**
