### PR TITLE
[#1941] Fix text overflow issue

### LINKED ISSUE #1941: Text overflow thenewboston_node.business_logic.blockchain.base.BlockchainBase
**Bug Description**
Mobile: Text overflow broke UI

**Steps to Reproduce**
1. Go to 'https://thenewboston.com/progress'
2. Click on 'blockchain'
3. Scroll down to 'last second issue'

**Expected behavior**
No overflow like this

**Actual behavior**
Text overflow

**Screenshots/Recordings**

**OS and Browser**
 - OS: Android
 - Browser: Chrome

**Additional context**
[this page](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Text/Wrapping_Text) can be used as a reference for css

 **Account Number**
> 6663b43af069d9d4d303cd1a13d63e9d206ab786eba694b3e23f4dfdb3670d34

### PR DESCRIPTION
**Pull request by Hamza091**
Fixed #1941 Text overflow Issue.

Account Number: f319d1ab0805e65a5a368e3c942a906fe04db4a5f0fb6ba721a5b97bf70ff135

### CODE REVIEW

**Comment by jamessspanggg** [comment]
can you provide a screenshot of the fix in effect?

**Comment by Hamza091** [comment]
> can you provide a screenshot of the fix in effect?

Sure

**Comment by Hamza091** [comment]
> can you provide a screenshot of the fix in effect?

ss

**Comment by jamessspanggg** [comment]
thanks @Hamza091 

Would `work-break: break-word` be a better solution? to prevent some short words to be split to the next line

**Comment by Hamza091** [comment]
> thanks @Hamza091
> 
> Would `work-break: break-word` be a better solution? to prevent some short words to be split to the next line

Yep, It would be better. Let me do the changes.

**Review by jamessspanggg — APPROVED** [review]

**Pull request merged**
