### PR TITLE
Signup modal

### PR DESCRIPTION
**Pull request by amarjeet987**
fixes: #461 

- Added a test modal as per the UI given.
- Brought most of the components necessary from Account-Manager to the website for modals and forms.
- Installed necessary packages ( formik, react-select, @types/react-select ).
- Test modal can be accessed from route "/account".

### CODE REVIEW

**Comment by Hristijan95** [comment]
Do we want all of the Formik components copied here, even though most of them are not being used right now? @thesanjeevsharma @lapstjup

**Review by charnysh-dev — COMMENTED** [review]
@amarjeet987 
It looks good. but I'd like to know why we should have both `components/FormElements` and `components/FormComponents`. I think there is a way to use one of them or integrate them. What do you think? 
FYI @buckyroberts

**Comment by amarjeet987** [comment]
@charnysh-dev  Yeah can be done ofc, I kept it that way to maintain the consistency between both the projects, account-manager and this. In account manager, we're already using stuff from both `components/FormElements` and `components/FormComponents`.

**Review by charnysh-dev — APPROVED** [review]

**Comment by charnysh-dev** [comment]
> @charnysh-dev Yeah can be done ofc, I kept it that way to maintain the consistency between both the projects, account-manager and this. In account manager, we're already using stuff from both `components/FormElements` and `components/FormComponents`.

Ok, then we could resolve some conflicts

**Review by thesanjeevsharma — APPROVED** [review]

**Pull request merged**
