### PR TITLE
hello world in chinese

### PR DESCRIPTION
**Pull request by alhuang2**
adding hello world in chinese

### CODE REVIEW

**Comment by shahraizali** [comment]
ISO Correct ✅
Spellings Correct ✅
Approved

**Comment by angle943** [comment]
hey @alhuang2 what is your account #?

**Comment by alhuang2** [comment]
It's  08b8b85b3a63615d295fd123ce7b7209b3650c550db6dccdf355ed6dbc048ec7

Thanks!

**Comment by Rajputusman** [comment]
Referring to issue id #351

**Pull request merged**
