### PR TITLE
336-Replace Homepage Social Media icons to SVG icons

### LINKED ISSUE #336: Replace Hompage Social Media Hero icons to use SVG Icons
prereq for this ticket: https://github.com/thenewboston-developers/Website/issues/335 - must be completed before this ticket

update these three icons to use the mdi-icons

Screen Shot 2020-10-29 at 11 44 34 PM

### PR DESCRIPTION
**Pull request by aayushi14**
closes #336

### CODE REVIEW

**Review by angle943 — CHANGES_REQUESTED** [review]
Can we make it look like the old ones? (dropshadow, thicker circular border, and changing color on hover)
Screen Shot 2020-10-31 at 11 58 57 AM

**Comment by angle943** [comment]
@aayushi14 you can take a look at my PR for inspiration: https://github.com/thenewboston-developers/Website/pull/343

in it, i had to make similar buttons (without shadow):

Screen Shot 2020-10-31 at 12 02 37 PM

The icon needs to be inside a circular div with a background color, and the icon itself is colored white.

Also, one more thing, let's update the Github icon to look like the topNav too:

Screen Shot 2020-10-31 at 12 03 54 PM

**Comment by aayushi14** [comment]
Got it.

**Comment by aayushi14** [comment]
image

**Review by angle943 — APPROVED** [review]

**Pull request merged**
