### PR TITLE
Made mobile drop down icon clickable

### LINKED ISSUE #1179: Mobile drop down icon not clickable
**Bug Description**
Clicking TopNavMobileMenu's drop down icons do not toggle show/hide. Clicking only the title will toggle show/hide.

**Steps to Reproduce**
1. Go to website home page with mobile device
2. Click on top right hamburger icon
3. Click on the drop down icon 
4. View that nothing happens

**Expected behavior**
Clicking on drop down icon should show/hide items

**Actual behavior**
Nothing happened 

**Screenshots/Recordings**
https://user-images.githubusercontent.com/32864116/103612713-f8d30b00-4f5f-11eb-8c03-2ad520814900.MP4

**OS and Browser**
 - OS: iOS safari

**Additional context**

**Account Number**
c54c04774efaae20746fd3f29cdd619fea512e119bc1082b863572b2e8844104

[How to Create an Account](https://thenewboston.com/account-manager/create-an-account)

### PR DESCRIPTION
**Pull request by AkinAguda**
Fixes #1179

### CODE REVIEW

**Comment by lapstjup** [comment]
Yo guys I have created a separate PR for this as well and changed the type of element and it's related CSS. It's #1224 . I want to prevent using absolute and hardcoded translate values.

**Comment by jamessspanggg** [comment]
> I want to prevent using absolute and hardcoded translate values.

I agree with this.

**Comment by AkinAguda** [comment]
I agree with this as well lol

**Comment by Rajputusman** [comment]
@AkinAguda Can I have your TNB account number so payment team can send you PR-reward. Thanks !

**Comment by AkinAguda** [comment]
> @AkinAguda Can I have your TNB account number so payment team can send you PR-reward. Thanks !

431f89d714dc2d748c899b14c725a52c2b5560c2b8e2bb2bb691f41a155c3a2e

**Pull request merged**
