### PR TITLE
Hello World in Albanian

### PR DESCRIPTION
**Pull request by DinShpati**
3b59cd93d7cb88fd55caaea77f07328b57cce7e3d1a14b13410291c698dccf2e

### CODE REVIEW

**Comment by Niekon01** [comment]
ISO: correct
Translation: correct
**Approved**

**Comment by thesanjeevsharma** [comment]
@odetolataiwo I have paid this earlier. Don't send coins. Can you make sure this is logged into the system?

**Comment by DinShpati** [comment]
> @odetolataiwo I have paid this earlier. Don't send coins. Can you make sure this is logged into the system?

Yes this is paid, I got the coins.

**Comment by odetolataiwo** [comment]
done


> @odetolataiwo I have paid this earlier. Don't send coins. Can you make sure this is logged into the system?

done

**Pull request merged**
