### PR TITLE
New Contributor added

### LINKED ISSUE #750: New Contributor
Team: Front-End Developers

{
  "title":Software Developer
  "isLead": false
  "payPerDay": 2800,
  "createdDate": "2020-11-12
  "contributor": {
    "contributorId":
    "displayName":Michael Lee
    "githubUsername":  tpikachu
    "profileImage":  tpikachu
    "slackUsername": Michael
  }
}

### PR DESCRIPTION
**Pull request by hasham56**
**Fixes #750 :**  Here is the Contributor added.

Capture

### CODE REVIEW

**Comment by manishram** [comment]
@hasham56 please close this PR.

**Comment by hasham56** [comment]
@manishram idk what happened but my solution was not accepted... 755 got accepted instead of 754... can u kindly ask someone what is the reason for this? did i do something wrong that i need to correct?

**Comment by manishram** [comment]
No @hasham56 your PR was correct but maybe sanjeev didn't notice you did PR first or because you didn't provide your account number in the description which I told you to add. But it's okay you can look for other issues. There are lots of issues still open. You can contribute to them.

**Comment by hasham56** [comment]
@manishram ok thanks

**Pull request closed without merging**
