### PR TITLE
Added Hello World in Hungarian language.

### PR DESCRIPTION
**Pull request by vilihegyi**
Regarding issue: #351 
I have added "Hello World" in Romanian and Hungarian languages.
My TNB Account Number is: `009073c5985d3a715c3d44a33d5f928e893935fbab206d1d676d7d8b6e27ec85`

### CODE REVIEW

**Comment by thesanjeevsharma** [comment]
@vilihegyi Please add one language only. Romanian is added by PR #599.

**Comment by vilihegyi** [comment]
@thesanjeevsharma Updated with Hungarian language only.

**Review by thesanjeevsharma — APPROVED** [review]

**Comment by thesanjeevsharma** [comment]
@odetolataiwo 500

**Comment by vilihegyi** [comment]
Thank you @thesanjeevsharma @odetolataiwo

**Pull request merged**
