### PR TITLE
Added marathi translation for Hello World

### PR DESCRIPTION
**Pull request by shcul333**
Accnt# c52424dacafed79abc730139eff7eec612873d650e938864b1c765fb5282d2fd

### CODE REVIEW

**Comment by Niekon01** [comment]
ISO: correct
Translation: correct
**Review required**

Please arrange your addition in alphabetical order of ISO. Thank you.

@angle943

**Comment by shcul333** [comment]
@Niekon01 Updated as per alphabetic order of ISO.

**Comment by thesanjeevsharma** [comment]
@odetolataiwo I have paid this earlier. Don't send coins. Can you make sure this is logged into the system?

**Comment by odetolataiwo** [comment]
> @odetolataiwo I have paid this earlier. Don't send coins. Can you make sure this is logged into the system?

done

**Pull request merged**
