### PR TITLE
Added 'Hello World' in Azerbaijani(AZ)

### PR DESCRIPTION
**Pull request by Kenan7**
I added the hello world in azerbaijani and turkish language.

### CODE REVIEW

**Review by thesanjeevsharma — CHANGES_REQUESTED** [review]
@Kenan7  You are only allowed to add one language. Please update your code to have a single language. You can remove Turkish, as we already have a PR #528 for it.

Also, please mention your account number when you create any PR.

**Comment by Kenan7** [comment]
a53bda6b74ee6dc97ac171233c972b6d4b9b7b924d2f3f8d300093f1ed8a4c8b

**Review by thesanjeevsharma — APPROVED** [review]

**Comment by Niekon01** [comment]
ISO: correct
Translation: correct
**Approved**

**Comment by thesanjeevsharma** [comment]
@Kenan7 Coins sent!

**Comment by thesanjeevsharma** [comment]
@odetolataiwo I have paid this earlier. Don't send coins. Can you make sure this is logged into the system?

**Pull request merged**
