### PR TITLE
Fixes: #523 Assets page 

### PR DESCRIPTION
**Pull request by manishram**
Fixes: #523 
1. Designed Assets page 
3. Assets page at "/assets"
2. Added Assets link to the navbar and footer

Account:
0f92e975101eb96cea80dce430d74efd3172fa229377818d467ded85dcf2ab6c

### CODE REVIEW

**Comment by manishram** [comment]
@thesanjeevsharma Don't merge the PR. Do a Review. Thanks

**Comment by lapstjup** [comment]
@manishram Can you share a screen recording of the above changes with responsive behaviour as well ?
@kristykjlee Is there a design for this or if there isn't, can you validate it once when the recording is shared ?

**Comment by manishram** [comment]
@kristykjlee @lapstjup 
Here is the recording:

1. For desktop:
assets-page-desktop

2. For Phone:
assets-page-phone

**Comment by manishram** [comment]
assets-page-desktop
assets-page-phone

**Comment by manishram** [comment]
Don't merge. Need to assign different links to download button for **TNB Logo** and another for **Logo Wordmark**. Currently, both download buttons download the same file from [thenewboston logos.zip ](https://github.com/thenewboston-developers/Website/files/5505472/thenewboston.logos.zip) which contains two folders. Need to make separate .zip file for those two folders.

**Comment by buckyroberts** [comment]
Not ready yet, asked him to submit a PR so I could take a look at something.

**Comment by manishram** [comment]
@thesanjeevsharma @kristykjlee

Updated the links for assets file download. PR is ready.

**Comment by lapstjup** [comment]
@kristykjlee Hey Kristy, is this design good to go ?

**Pull request merged**
