### PR TITLE
issue#909 - Long title words break the mobile design in the tasks page

### PR DESCRIPTION
**Pull request by mersimoski**
The titles that were big without spaces pushed the prices out of view, so i added a word break to keep mobile responsiveness.

From this:
image

To this:
image

Acc nr:
cf59a784ff69e64e977359f28cd4d04c0aea7a37cf1b8bda3dfbde2364032855

### CODE REVIEW

**Comment by Hristijan95** [comment]
@mersimoski , we don't wanna use `!important` as stated here: https://thenewboston.com/style-guide/css
Also, please reference this PR to the issue.

**Comment by mersimoski** [comment]
for this issue its just added word-break nothing else

**Comment by lapstjup** [comment]
@mersimoski Use the word-wrap mixin available in **styles/_mixins.scss**. Also one PR should address one issue. You can raise separate PR for language addition and anything else which isn't related to this particular issue.

**Comment by mersimoski** [comment]
@lapstjup i was just searching on how to send just PR for one issue and not to send every commit i have made.

**Pull request closed without merging**
