### PR TITLE
Add Hello World in Kurdish

### PR DESCRIPTION
**Pull request by A-A-2**
#351 
Account Number: bc7decf57ad5d66601b6ca291cf9f3fb798ccab97b2836a9b5a521f3a2f70b97

### CODE REVIEW

**Comment by Niekon01** [comment]
ISO: correct
Translation: It says "Hi World" in Google Translate. Can you please confirm if this is correct? If you could, please change you to "Hello World" instead.
**Review required**

@angle943

**Comment by A-A-2** [comment]
Well there is no different in Kurdish. All "Hello", "Hi", "Hey" are "Silav"

**Comment by thesanjeevsharma** [comment]
@odetolataiwo I have paid this earlier. Don't send coins. Can you make sure this is logged into the system?

**Comment by odetolataiwo** [comment]
> @odetolataiwo I have paid this earlier. Don't send coins. Can you make sure this is logged into the system?

done

**Pull request merged**
