### PR TITLE
Hello world in Kannada

### PR DESCRIPTION
**Pull request by avinashupadhya99**
Issue #351 Added Hello World in Kannada

### CODE REVIEW

**Comment by Niekon01** [comment]
ISO: correct
Translation: correct
**Approved**

**Comment by thesanjeevsharma** [comment]
@avinashupadhya99 Please comment your account number so I can send you coins! If you don't have an account you can create one by downloading the app.

**Comment by avinashupadhya99** [comment]
My account number - `94cf53921e9c5ddf48dc5589b7cdf111f7acdc93dc3073b94880416d4676b9ae` . Thank you.

**Comment by thesanjeevsharma** [comment]
@odetolataiwo 500 coins!

**Pull request merged**
