### PR TITLE
Test: DocContainer 

### LINKED ISSUE #1344: UNIT TESTS - components/DocWrapper/DocContainer
## What

Create unit tests using [Jest](https://jestjs.io/en/) and [React Testing Library](https://testing-library.com/docs/react-testing-library/intro/).

Here are a couple examples of how unit tests should be created:

1. [Unit tests for our A component](https://github.com/thenewboston-developers/Website/blob/development/src/components/A/A.test.tsx)
2. [Unit tests for Icon component](https://github.com/thenewboston-developers/ui-js/blob/master/src/components/Icon/Icon.test.tsx)
3. [Unit tests for Button component](https://github.com/thenewboston-developers/ui-js/blob/master/src/components/Inputs/Button/Button.test.tsx)

## General Acceptance Criteria for writing Unit tests

1. Should create a `[nameOfComponent].test.tsx` within the same directory of the component.
2. Should have tests that tests every `prop` of the component.
3. If there are any conditional logic within the component, there should be unit tests that accounts for each conditional branches.
4. `npm run test` should be passing.

## Specific Acceptance Criteria

1. make sure you tests for each prop

### PR DESCRIPTION
**Pull request by PrinceRajRoy**
Resolves #1344

### CODE REVIEW

**Comment by PrinceRajRoy** [comment]
@angle943 let me know if I can improve on anything and if Regex on lastUpdated prop is required, I'm a bit new to writing tests.

**Comment by angle943** [comment]
@PrinceRajRoy these are excellent. Good job!

**Review by angle943 — APPROVED** [review]

**Comment by Rajputusman** [comment]
Can I have your TNB account number, so I can send **PR-reward**?

**Comment by PrinceRajRoy** [comment]
@Rajputusman Added

**Pull request merged**
