### PR TITLE
Fix code highlighting in documentation

### LINKED ISSUE #733: [Documentation] Code segments under CSS / SASS not highlighted properly
**Bug Description**
The code segments within the CSS / SASS section are not highlighted properly, especially  `jsx` code segments.

**Steps to Reproduce**
1. Go to Documentation -> CSS /SASS
2. Scroll to [Block Elements](https://thenewboston.com/style-guide/css#blocks-elements)
3. View that the jsx code segments are not highlighted properly

**Expected behavior**
The JSX code should be highlighted properly.

**Actual behavior**
The JSX code not highlighted properly, some parts are white in colour.

**Screenshots/Recordings**
Screen Shot 2020-11-11 at 9 39 27 PM

**OS and Browser**
 - OS: Mac, Chrome

**Additional context**
May be due to not up-to-date `react-syntax-highlighter` package.

**Account Number**
c54c04774efaae20746fd3f29cdd619fea512e119bc1082b863572b2e8844104

[How to Create an Account](https://thenewboston.com/account-manager/create-an-account)

### PR DESCRIPTION
**Pull request by jamessspanggg**
Fixes #733 

Update react-syntax-highlighter to the latest version and the highlighting works fine.

Fixed a small typo in the meantime.

Account Number: c54c04774efaae20746fd3f29cdd619fea512e119bc1082b863572b2e8844104

### CODE REVIEW

**Comment by jamessspanggg** [comment]
Before:
Screen Shot 2020-11-11 at 9 39 27 PM

After:
Screen Shot 2020-11-11 at 9 39 51 PM

**Review by amarjeet987 — APPROVED** [review]
@thesanjeevsharma 
- react-syntax-highlighter updated to latest version.

**Comment by jamessspanggg** [comment]
@lapstjup there seems to be issues when the highlighter language is set to `jsx`, which makes the highlighting inconsistent. For example, the following code segment is not detected correctly when set as `jsx`:

```
return (
  <div className={\`LeftNav__nav \${selected === 'home' ? 'LeftNav__nav--active' : ''}\`}>Home</div>
);
```

I have played around with other languages and setting them to `typescript` seems to work best as it standardises all code segments. With this change there wouldn't be any inconsistencies in terms of colours

**Comment by accessdeniedIT** [comment]
@jamessspanggg your code does not follow the styles guide, https://thenewboston.com/style-guide/react, please fix the issues, if you need any help seting your VS-CODE to run prettier after saving, I'll be happy to help.
index.tsx needs styling.

**Comment by jamessspanggg** [comment]
hi @accessdeniedIT thanks for spotting the mistake. I ran prettier beforehand, it's just that the code segment is surrounded within a string, which wont be detected by prettier. Have updated the indentation accordingly.

**Comment by jamessspanggg** [comment]
> panggg your code does not follow the styles guide, https://thenewboston.com/style-guide/react, please fix the issues, if you need any help seting your VS-CODE to run prettier after saving, I'll be happy to help.
> index.tsx needs styling.

Another thought, since the code style is currently being checked manually, should we setup CI in order to check code styles in every PR?

**Comment by accessdeniedIT** [comment]
I don't have permission for that, but I'll bring it up to the leads, either way, as long as you setup up your IDE properly this shouldn't be an issue

**Comment by accessdeniedIT** [comment]
@jamessspanggg have you made the manual changes?

**Comment by jamessspanggg** [comment]
> @jamessspanggg have you made the manual changes?

Yep done so

**Comment by accessdeniedIT** [comment]
make sure you push correctly because I can't see the changes.

**Comment by jamessspanggg** [comment]
> make sure you push correctly because I can't see the changes.

It's in my most recent commit in this PR [here](https://github.com/thenewboston-developers/Website/commit/0ac440b5defa03f4b3d40f93c9c2152c0d03e445)? Or am I missing what you wanted me to change

**Comment by accessdeniedIT** [comment]
167 |       <DocSubSection id={StyleGuideCssNav.sassAmpBem} title="SASS Ampersand + BEM">
  168 | @@ -181,7 +183,7 @@ const LeftMenu: FC = () => {
> 169 |    </div>
      |     ^
  170 | );`}
  171 |           heading="LeftMenu.tsx"
  172 |           language={SnippetLang.jsx}

and other compile errors

**Comment by accessdeniedIT** [comment]
@jamessspanggg it's still not formatted properly

**Comment by jamessspanggg** [comment]
> @jamessspanggg it's still not formatted properly

@accessdeniedIT sorry but I cannot reproduce what you provided. I have ran `npm run lint`, `npm run prettier` and `npm run start` locally and all works fine without any compilation error.

Are you on the correct branch? Did you pull the latest changes? Did you run `npm install`?

**Comment by accessdeniedIT** [comment]
ok I did a manual update, it it fixed the issues based on your latest reference to the change

**Review by accessdeniedIT — APPROVED** [review]

**Pull request merged**
