### PR TITLE
Fixes: #648 teams.json ordered

### PR DESCRIPTION
**Pull request by manishram**
Fixes: #648 

1. Fixed: contributorId 33 and 34 repetitions.  
2. Fixed: contributorId 14 and 16 missing.
3. Fixed: Some team members were not ordered properly by contributorId.
4. Reassigned new contributorId to contributors whose previous contributorId were greater than 13.

Account:
0f92e975101eb96cea80dce430d74efd3172fa229377818d467ded85dcf2ab6c

### CODE REVIEW

**Comment by lapstjup** [comment]
@thesanjeevsharma even though this PR resolves the numbering, I feel that the data structure for the object could have been like in openings. Here we have segregated teams as per **title** and then so each object has one title and respective contributors and then we have array of such title objects. 

Could this be made simple by adding category as a property like we have in openings ? Let me know your thoughts on this. For now I think the changes are okay and can be merged.

**Review by lapstjup — APPROVED** [review]

**Review by lapstjup — CHANGES_REQUESTED** [review]
Let's wait for a clarification.

**Comment by thesanjeevsharma** [comment]
@lapstjup I checked the files. The last PR that was merged introduced those duplicate IDs. Let's fix only those and leave everthing as it is.

I am closing this.

**Comment by manishram** [comment]
@thesanjeevsharma Just need to assign new id to duplication of 33 and 34?

**Pull request closed without merging**
