### PR TITLE
Add Display Name field in the sign up

### PR DESCRIPTION
**Pull request by manishram**
Fix: https://github.com/thenewboston-developers/Website/issues/1489

Account Number: `0f92e975101eb96cea80dce430d74efd3172fa229377818d467ded85dcf2ab6c`

### CODE REVIEW

**Review by amarjeet987 — COMMENTED** [review]
@angle943 Can the user use numbers / special characters in the display name?
If not, @manishram you can put up some html pattern kinda thingy like "[a-zA-Z]*"  for the input to prevent the user from using numbers and special characters in the display name.

**Comment by manishram** [comment]
I thought that too but then realised maybe people would like to use display names like **Chri$to4** instead of **Christopher**. 😂

 Let's see what Justin say.

**Comment by angle943** [comment]
Good points, for now, lets just do these two:

1) no whitespaces on the left & right (we can probably just `trim` the field before sending it off to the BE)
2) max length of `30` (instead of using `yup` for this, we can probably just use `max_length` on the `Input`. Or if our `Input` is not configured to accept that, you can use `yup` validation for that

**Review by angle943 — CHANGES_REQUESTED** [review]
look at comments above

**Comment by jamessspanggg** [comment]
Added the trimming of display name before sending to BE, also added the 30 character limit with yup. Our current `Input` does not handle it.

cc @angle943 @manishram

**Comment by manishram** [comment]
Thanks, @jamessspanggg I got busy with Weekly Reports.

**Review by angle943 — APPROVED** [review]

**Comment by manishram** [comment]
Hey, @jamessspanggg can you give me your acc # so that I can send you 250coins for helping me out in this PR.

**Pull request merged**
