### PR TITLE
Pashto language added

### PR DESCRIPTION
**Pull request by naveedahmad99**
Pashto language added

Account Number: 04ab47908bf0e72161f1b4c3b93e87c3d09b8e20162c220e3284972e3f82ab2b

### CODE REVIEW

**Review by thesanjeevsharma — APPROVED** [review]

**Comment by thesanjeevsharma** [comment]
@naveedahmad99 Thank you for your contribution!

**Review by thesanjeevsharma — CHANGES_REQUESTED** [review]
@naveedahmad99 You have placed it wrong. It should come above `pt` in alphabetical order. 

Please make this change.

**Review by naveedahmad99 — COMMENTED** [review]
Applied Changes

**Review by thesanjeevsharma — APPROVED** [review]

**Comment by thesanjeevsharma** [comment]
@odetolataiwo I have paid this earlier. Don't send coins. Can you make sure this is logged into the system?

**Comment by odetolataiwo** [comment]
> @odetolataiwo I have paid this earlier. Don't send coins. Can you make sure this is logged into the system?

done

**Pull request merged**
