### PR TITLE
[#679] Fix leaderboard drop down

### LINKED ISSUE #679: [Leaderboard] Dropdown does not work
**Bug Description**
Within the leaderboard page, when using tablet or mobile phones, toggling the dropdown does not show anything.

**Steps to Reproduce**
1. With a device that is smaller than desktop, i.e. phone or tablet, go to leaderboard page
2. Click on drop down button
3. View that nothing is shown

**Expected behavior**
The drop down of repositories should be shown.

**Actual behavior**
Nothing is shown in drop down.

**Screenshots/Recordings**
leaderboard_dropdown

**OS and Browser**
 - OS: iOS, iPAD OS
 - Browser: Chrome, safari

**Additional context**
can also be reproduced by resizing ur desktop to the appropriate width (smaller than 992px)

**Account Number**
c54c04774efaae20746fd3f29cdd619fea512e119bc1082b863572b2e8844104

[How to Create an Account](https://thenewboston.com/account-manager/create-an-account)

### PR DESCRIPTION
**Pull request by jamessspanggg**
Fixes #679

The dropdown nav links are not appearing when screen size is less than 992px.

Currently the nav links in the leftMenu and the dropdown both share the same className `Leaderboard__left-menu`. The `Leaderboard__left-menu` className will be set to `display: none` when the screen size is less than 992px, which causes both nav links to disappear.

Placing the `Leaderboard__left-menu` className to be specific for the left menu nav links will solve the issue of the dropdown nav links not appearing.

Account Number: c54c04774efaae20746fd3f29cdd619fea512e119bc1082b863572b2e8844104

### CODE REVIEW

**Comment by jamessspanggg** [comment]
Working dropdown:

working_dropdown

**Comment by jamessspanggg** [comment]
hi @lapstjup is it possible to add the `not paid` label?

**Comment by lapstjup** [comment]
@jamessspanggg Don't worry, we have a tracking system for this.

**Comment by jamessspanggg** [comment]
> @jamessspanggg Don't worry, we have a tracking system for this.

ok noted with thanks!

**Pull request merged**
