### PR TITLE
Update hello-world.ts malayalam

### PR DESCRIPTION
**Pull request by KevinKurian7**
changed the malayalam text of hello world to its native phrase

### CODE REVIEW

**Comment by Hristijan95** [comment]
@KevinKurian7 , can you explain what do you mean but "native phrase"? Because we can't know which one is true, but according to google translate, the old one is the correct one, however I know that google translate can be wrong, so please explain what is what and I'll handle the issue.

**Comment by aasifrafeeq** [comment]
in malayalam the meaning of  world is ലോകം

**Comment by KevinKurian7** [comment]
> @KevinKurian7 , can you explain what do you mean but "native phrase"? Because we can't know which one is true, but according to google translate, the old one is the correct one, however I know that google translate can be wrong, so please explain what is what and I'll handle the issue.

what i meant by converted to native phrase  was that the text which was there for hello world was just literally saying hello world itself in Malayalam text but still as an English  word with the Malayalam alphabets
ഹലോ വേൾഡ്---original text ---pronounced hello world

നമസ്‌കാരം  ലോകമെ---text I suggested--
നമസ്‌കാരം  (pronounced  namaskaram meaning hello in English)
ലോകമെ       (pronounced lokame meaning world in malayalam)

It does not show up in google translate as you said when directly translating "hello world".

**Review by amarjeet987 — COMMENTED** [review]
The initial one translates to "Hello World" and the new one to "Hello world", since we've the "World" in the website for the English text, idk let's go with that everywhere for the sake of consistency.

**Comment by Hristijan95** [comment]
@KevinKurian7 , what is wrong with the existing one, what's incorrect?

**Pull request closed without merging**
