### PR TITLE
Remove team member from Teams Page #1297

### PR DESCRIPTION
**Pull request by achalpatel**
Removed David Yap from Design Team
Removed Chibuzor from Marketing Team
Removed Martyn from New User Operation team

EDIT: I removed Ijeoma - Justin

### CODE REVIEW

**Review by amarjeet987 — CHANGES_REQUESTED** [review]
Please mention the issue that is fixed in the PR while making the PR.

**Comment by achalpatel** [comment]
> Please mention the issue that is fixed in the PR while making the PR.

Sorry, this is my first time contribution. By mentioning the issue, you mean adding the issue in the title of the PR, right?

**Comment by angle943** [comment]
@achalpatel the issue number please

**Comment by amarjeet987** [comment]
> > Please mention the issue that is fixed in the PR while making the PR.
> 
> Sorry, this is my first time contribution. By mentioning the issue, you mean adding the issue in the title of the PR, right?

Yeah basically the link to the issue that is fixed.

**Comment by achalpatel** [comment]
Issue:  #1297

**Comment by Rajputusman** [comment]
@achalpatel Can I know your TNB account number, so I can send you PR-reward?

**Comment by achalpatel** [comment]
Account number : 3916866c24a8bdded1068a691b60e7dc2dca0bc68de7252d74e4816b1e56efac

**Pull request merged**
