### PR TITLE
[Job Update]: Added Marketing Specialist Job from India

### PR DESCRIPTION
**Pull request by Lalisfeed**
- Added Marketing Specialist Job from India
- Mentioned country names in positions
- Configured URL part (openingId) with country names
- Arranged Marketing Specialists in Alphabetical order based on country names
- Placed SEO specialist at the top and all the marketing specialists after it

PR in reference to #1961  & #1963

### CODE REVIEW

**Comment by angle943** [comment]
@Lalisfeed what is your account number?

**Comment by Lalisfeed** [comment]
It's 
> 6663b43af069d9d4d303cd1a13d63e9d206ab786eba694b3e23f4dfdb3670d34

**Comment by Lalisfeed** [comment]
When will the PR be merged?

**Comment by jamessspanggg** [comment]
please resolve conflicts @Lalisfeed

**Comment by jamessspanggg** [comment]
also @Lalisfeed would be good if your PR description includes the `Fixes #[issue-number]` so that when merging the PR, its corresponding issues will be automatically closed

**Pull request closed without merging**
