### PR TITLE
Added Hello World in German

### PR DESCRIPTION
**Pull request by jagdisharma**

### CODE REVIEW

**Comment by jagdisharma** [comment]
My account number: 36846b3d4bfdfbeee3b66f6a5b8cc671b3b92e7c4dc5203b0ab941a953945cc1

**Comment by shahraizali** [comment]
ISO Incorrect ❌ (GE is for Georgia) Source: https://www.iban.com/country-codes
Spellings Correct ✅
Changes Required

**Comment by jagdisharma** [comment]
Changed ISO for German

**Comment by shahraizali** [comment]
ISO Correct ✅
Spellings Correct ✅
Approved

**Pull request merged**
