### PR TITLE
Add how to set up payment board docs

### LINKED ISSUE #990: Add How to Set Up Payment Board Docs
Add How to Set Up Payment Board documentation to the Internal documents section on the website.

- New User Operations - https://thenewboston.com/internal/new-user-operations
- Team Lead Onboarding - https://thenewboston.com/internal/team-lead-onboarding
- Product Development - https://thenewboston.com/internal/product-development
- **How to Set Up Payment Board - translate attached PDF to React**

[TNB Payments.pdf](https://github.com/thenewboston-developers/Website/files/5580660/TNB.Payments.pdf)

### PR DESCRIPTION
**Pull request by jamessspanggg**
Fixes #990 

Snapshot of docs:
Screen Shot 2020-11-25 at 1 14 23 AM
Screen Shot 2020-11-25 at 1 14 33 AM
Screen Shot 2020-11-25 at 1 14 38 AM

Acc no: c54c04774efaae20746fd3f29cdd619fea512e119bc1082b863572b2e8844104

### CODE REVIEW

**Comment by lapstjup** [comment]
@mersimoski Review this PR for responsiveness.

**Comment by lapstjup** [comment]
@jamessspanggg Hey I was thinking that wherever double quotes have been used, if we could use <b> tag to highlight them ? What do you think ?

**Comment by jamessspanggg** [comment]
> @jamessspanggg Hey I was thinking that wherever double quotes have been used, if we could use **bold** tag to highlight them ? What do you think ?

Yep sounds good, I think that will make the highlighted text more obvious and stand out more. Am on it

**Comment by jamessspanggg** [comment]
@lapstjup I observed that the internal option tab is not available in the top nav, visitors would have to visit the project proposals page in order to know that there is an internal section. 

Is this on purpose since it's for internals? Or should we include the `Internal` option tab under the `More` dropdown in the top nav?

**Comment by lapstjup** [comment]
@jamessspanggg Need to confirm on this.

**Comment by lapstjup** [comment]
@jamessspanggg Can you give this one proof read to correct any grammatical/language errors if any ?. Give me a good to go and I will merge it post that.

**Comment by jamessspanggg** [comment]
@lapstjup may i know the exact 4 color codes used for the `Paid`, `Not Paid`, `Bug Bounty` and `PR Reward` labels? I don't have edit access on the labels as I'm not a internal contributor. I believe it's important to place the exact color code in this documentation as some of the front end matches the issue label based on colour.

**Comment by lapstjup** [comment]
Bug Bounty Owed - #b60205
Not Paid - #e99695
Paid - #fbca04
PR Reward - #09825d

**Comment by jamessspanggg** [comment]
@lapstjup fixed some grammatical errors and added the colour codes for clarity. The section looks good to me now.

**Comment by lapstjup** [comment]
@jamessspanggg Your choice of label hex gave me an idea to instead use `<Label../>` component. Also thought of removing some stuff since we are showing colors here. What do you think ?

**Comment by jamessspanggg** [comment]
> @jamessspanggg Your choice of label hex gave me an idea to instead use `<Label../>` component. Also thought of removing some stuff since we are showing colors here. What do you think ?

yep looks awesome! saved the need to load one image and looks better 👍🏻

**Comment by jamessspanggg** [comment]
> @lapstjup I observed that the internal option tab is not available in the top nav, visitors would have to visit the project proposals page in order to know that there is an internal section.
> 
> Is this on purpose since it's for internal usage? Or should we include the `Internal` option tab under the `More` dropdown in the top nav?

@lapstjup any updates on this?

**Comment by AbhayAysola** [comment]
@jamessspanggg I think all the Internals will go into a resources tab in the teams/All page. #1013

**Pull request merged**
