### PR TITLE
Hello world in UK and RU

### PR DESCRIPTION
**Pull request by vosi**

### CODE REVIEW

**Comment by angle943** [comment]
@vosi sorry only one per person! you gotta pick one :(. Which one do you want to add? 

Also, what is your account #?

**Comment by vosi** [comment]
@angle943 we are bilingual in Ukraine
dont mind about the account #, I dont have one :)

**Review by angle943 — APPROVED** [review]

**Comment by angle943** [comment]
@vosi i'll add ukraine for now. I want to give as many people as possible to do this, so we'll just add one language.

And aww, let me know in the future if you decide to create an account #, i'll send you 500 coins once you do!

**Comment by angle943** [comment]
#351

**Pull request merged**
