### PR TITLE
added transition instead simple pop on openings

### PR DESCRIPTION
**Pull request by rupamkairi**
## Added transition effect on the Openings page 

Added transition on OpeningsOpening class.

https://user-images.githubusercontent.com/33358148/111327064-1248af80-8693-11eb-98e4-06cd38c4ca39.mp4

Hope this is not against your styleguides.

### CODE REVIEW

**Comment by amarjeet987** [comment]
Is it related to some reported issue?

**Review by amarjeet987 — COMMENTED** [review]
Is it related to some reported issue?

**Comment by rupamkairi** [comment]
No, I don't think it was mentioned in any issue. I did this as a visual improvement.

**Comment by angle943** [comment]
i like it, except we have a lot of cards that should all have consistent UX experience, so closing for now

**Pull request closed without merging**
