### PR TITLE
Adding hello world in malayalam

### PR DESCRIPTION
**Pull request by aasifrafeeq**
hello world in malayalam corrected
account no : f4b5b9202e6fc3ccf09969a8118df3c58c3a0a9f692ac9e3070af5b916822731

### CODE REVIEW

**Comment by Hristijan95** [comment]
@aasifrafeeq , please tell me what's the difference between "ഹലോ ലോകം" and "ഹലോ വേൾഡ്". On google translate "ഹലോ വേൾഡ്" is a verified translation and matches with the existing record in hello-world.ts.

**Comment by aasifrafeeq** [comment]
വേൾഡ് is just the word world in malayalam but ലോകം is the meaning of world in malayalam. U can check by transilating the word world in google translate

**Comment by aasifrafeeq** [comment]
Screenshot_20201112-070833_Chrome

**Review by amarjeet987 — COMMENTED** [review]
Google translates both to "Hello world" (new one) and "Hello World" (initial one). Since the English one in the website is with an uppercase "W", idk let's go with that for sake of consistency.

**Comment by aasifrafeeq** [comment]
Ok then, will i still earn any coins.

**Comment by Hristijan95** [comment]
@aasifrafeeq , thanks for the effort. If you want to earn coins and contribute, feel free to open a PR for any of the other issues.

**Pull request closed without merging**
