### PR TITLE
[#1602] Remove leaderboard page, related data, utils and components

### LINKED ISSUE #1602: Scrap leaderboards
we are going to get rid of leaderboards page: https://thenewboston.com/leaderboard/All

remove all components related to it, all util functions related to it (if any), the routes, from header, footer, etc. Erase the associated data files too

### PR DESCRIPTION
**Pull request by jamessspanggg**
Fixes #1602 

Bye bye leaderboard, for now :'(

### CODE REVIEW

**Comment by dhakal0kushal** [comment]
:(

**Review by thesanjeevsharma — CHANGES_REQUESTED** [review]
@jamessspanggg you forgot to remove it from the homepage.
Under hero section, 3rd point.

Rest is fine.

**Comment by jamessspanggg** [comment]
> @jamessspanggg you forgot to remove it from the homepage.

Modified, also reverted the removal of data as it is used by the `Profile` page's `TasksCompleted` section.

**Comment by angle943** [comment]
looks good!

**Pull request merged**
