### PR TITLE
Docs update

### PR DESCRIPTION
**Pull request by Reeler**
I fixed some grammatical errors in the readme file.

### CODE REVIEW

**Comment by Hristijan95** [comment]
This is contributing to #643 . Some of the texts were fixed in #646 , but there are a few more here, so I'll merge this one as well. @odetolataiwo , 500.

**Comment by Reeler** [comment]
do i get paid

**Comment by Hristijan95** [comment]
@Reeler , yes, you will receive coins when the Head of Contributor Payments picks up this issue.

**Comment by Reeler** [comment]
ok cool

**Comment by Reeler** [comment]
aa4d2b47910a3583e5b8b14219e9462f3a063d65df90fdb587024bbfe3de055e

**Pull request merged**
