### PR TITLE
965-updated docs for Primary Validator - Config

### LINKED ISSUE #965: Update Docs for Primary Validator - Config
Update documentation and sample code for Primary Validator - Config
- ensure all available endpoints (`GET`, `POST`, `PATCH`, and `DELETE`) are documented
- update request and response examples from real API data (2 items for `GET` list responses)
- JSON should be formatted with 2 space indents
- ensure any/all params are documented in tables
- https://thenewboston.com/primary-validator-api/config

### PR DESCRIPTION
**Pull request by aayushi14**
closes #965

### CODE REVIEW

**Review by shahraizali — APPROVED** [review]

**Comment by Hristijan95** [comment]
@aayushi14, the JSON should be formatted with 2 spaces indents as specified in the issue, please format it when you get the chance.

**Comment by aayushi14** [comment]
@Hristijan95 It is currently formatted with 2 space indents. And it looks perfect on the website. Can you show me how it should look like?

**Comment by Hristijan95** [comment]
Hmm, @aayushi14 , I will check later. If it's okay on your end, ignore all other comments I added, could be something on my end.

**Comment by Hristijan95** [comment]
@aayushi14 looks like it's not okay, here's an image of what I am trying to say:
Screen Shot 2020-11-26 at 00 55 07

**Comment by aayushi14** [comment]
So we need 2 space and 4 space indents? Bucky mentioned to have 2 space indents.

**Pull request merged**
