### PR TITLE
added Latvian language

### PR DESCRIPTION
**Pull request by Zims**
Added Latvian (lv) language.
My address:
62e2762010196c45ec6d06a218db6ae37816d5ab2e7cd37f9b4e01d016917cf4

### CODE REVIEW

**Comment by thesanjeevsharma** [comment]
@Zims On google translate, it shows - Healthy World. Are you sure this is the correct translation?

**Comment by Zims** [comment]
Healthy and "sveika" have close to the same meaning but "Sveika pasaule" is def. correct. 
Google translate doesn't get the context

**Comment by thesanjeevsharma** [comment]
@odetolataiwo I have paid this earlier. Don't send coins. Can you make sure this is logged into the system?

**Comment by odetolataiwo** [comment]
> @odetolataiwo I have paid this earlier. Don't send coins. Can you make sure this is logged into the system?

done

**Pull request merged**
