### PR TITLE
Bosnian hello world

### PR DESCRIPTION
**Pull request by whitelionx**
fb84a32a698a03dd327c4ce673f19fa0acf6e68cb50f143d5d7c080471bc4625

Now the ISO code should be correct.
The Bosnian language is similar/almost the same to Serbian and Croatian: https://en.wikipedia.org/wiki/Bosnian_language

image

### CODE REVIEW

**Comment by Niekon01** [comment]
ISO: correct
Translation: correct
Approved

**Comment by whitelionx** [comment]
Are there some issues or can it be merged @Niekon01   😃 I hope everything is fine

**Comment by Niekon01** [comment]
Justin will merge them when he finds time, and you will receive your payment. Please be patient. 🙂

**Comment by whitelionx** [comment]
Thanks for the info, was just wondering if everything was fine 😄 @Niekon01

**Comment by thesanjeevsharma** [comment]
@odetolataiwo I have paid this earlier. Don't send coins. Can you make sure this is logged into the system?

**Comment by odetolataiwo** [comment]
> @odetolataiwo I have paid this earlier. Don't send coins. Can you make sure this is logged into the system?

done

**Pull request merged**
