### PR TITLE
Openings - Hiring Freeze #738 Fixed!

### PR DESCRIPTION
**Pull request by Akshit1311**
Fixed Hiring Freeze Page, previous code commented.

My Account Number : deafdd8531213a77bfc51da798a5d9b4907e2d618af199c67c851d7f7d564f13

### CODE REVIEW

**Comment by aayushi14** [comment]
Fixes #738

**Comment by Akshit1311** [comment]
Umm, I didn't receive any points for this pull request

**Comment by aayushi14** [comment]
Once you get paid, you will see a Yellow tag "Paid" on this PR. You will get a notification (if you have enabled notifications) when any tag is assigned.

**Comment by Akshit1311** [comment]
Okayy, thanks a lot!

**Pull request merged**
