### PR TITLE
Add project openings to website

### LINKED ISSUE #1270: Add Project's openings to the website
We have openings for the projects here: 
https://github.com/thenewboston-developers/Project-Proposals/blob/master/Openings/openings.md

We need to move these opening to the openings of the website, here https://thenewboston.com/openings/All

### PR DESCRIPTION
**Pull request by AbhayAysola**
Closes #1270

### CODE REVIEW

**Comment by thesanjeevsharma** [comment]
@angle943 Take a look at this.

I think instead of creating a separate category we should classify them into existing categories and add a text below the heading
> This position is for - ABC App

When no text is added that means the opening is for the TNB team.
What do you think?

**Review by angle943 — CHANGES_REQUESTED** [review]
There's something weird that happens when you click on `UI/UX designer` and try navigating away. It persists up at top here.

I like @thesanjeevsharma 's idea. I don't think we should be creating extra categories.

Screen Shot 2021-02-10 at 6 40 12 PM

**Comment by AbhayAysola** [comment]
Alright, so I should make a category called "Project Proposal Openings" ?

**Comment by AbhayAysola** [comment]
I added the Project Proposals category and a small part in the description which says which proposal the opening is from. I am still working on the bug which @angle943 found, but I can't figure out why that's happening. Any ideas?

**Comment by thesanjeevsharma** [comment]
@AbhayAysola 

I was thinking to add an extra optional field on Opening - `projectName`.

If this exists you'll know it belongs to a project, so you'll put a highlighted(some styling that is easily noticeable at a glance but not too striking that it diverts the attention) text below the position title - `This position is for {projectName}.`

All the openings will fall under existing categories, i.e. engineering, design, etc.

I'll check your issue, tonight. At work rn.

**Comment by jamessspanggg** [comment]
> There's something weird that happens when you click on `UI/UX designer` and try navigating away. It persists up at top here.

This is currently occurring as there is duplicated key: `position` (UI/UX designer) that is being passed to the openings and it interrupts React's reconciliation phase. We should probably change the key to pass `openingId` instead.
https://github.com/thenewboston-developers/Website/blob/c6226e3d988d7880e58f98e56f17ae96f9e50893/src/containers/Openings/index.tsx#L65-L76

**Comment by AbhayAysola** [comment]
So I added the optional projectName field on opening like @thesanjeevsharma said, and also styled it a little. I changed the key to use `openingId` instead of `position` and it fixed the bug. I didn't push that though, because I wasn't sure if it would impact other parts of the page. @jamessspanggg just wanted to make sure if passing `openingId` won't break anything else.

**Comment by jamessspanggg** [comment]
> I didn't push that though, because I wasn't sure if it would impact other parts of the page. @jamessspanggg just wanted to make sure if passing `openingId` won't break anything else.

It shouldn't break if the `openingId` is unique, we prolly need a way to structure the `openingId` such that it will be unique every time someone adds a new opening.

**Comment by AbhayAysola** [comment]
> It shouldn't break if the `openingId` is unique, we prolly need a way to structure the `openingId` such that it will be unique every time someone adds a new opening.

Ah okay, so we should be good for now I think. We can do something like adding the `category` or `projectName` to the beginning of the `openingId` to make it more unique.

**Review by thesanjeevsharma — APPROVED** [review]
image
image

@jamessspanggg @angle943 thoughts?

**Comment by jamessspanggg** [comment]
> image
> image
> 
> @jamessspanggg @angle943 thoughts?

Would it be better if we provide the url to the corresponding project proposal or website (if any), so that people that are interested can view more details about the project straight away?

Something like:
```
project: {
    name: string;
    url: string;
}
```

**Comment by angle943** [comment]
@jamessspanggg @thesanjeevsharma yeah that would be great.

For the given data:
```
project: {
   name: string;
   url: string;
}
```

if the URL is provided, let's have the name of the app be the link, ie:

**Comment by AbhayAysola** [comment]
So I added the anchor tag, let me know what you guys think.

**Comment by AbhayAysola** [comment]
So I added the anchor tag, let me know what you guys think.

**Comment by angle943** [comment]
please resolve the merge conflicts so that I can review

**Review by thesanjeevsharma — APPROVED** [review]

**Comment by angle943** [comment]
@AbhayAysola @thesanjeevsharma I've removed the generic `span` css selectors, but other than that this is solid work. Thanks guys.

@AbhayAysola i've upped the bounty for this issue for the new acceptance criterias

**Comment by AbhayAysola** [comment]
@angle943 okay, cool. Here's my account number `8928526805de48e4bf2ed2a9b4b839e6b2603018ecdfbf4cffdb2065e01a3ed1` if I'm still going to get paid, since a lot of the work wasn't done by me.

**Comment by angle943** [comment]
@AbhayAysola yep you'll get paid. Can you post your account number on the `issue` too? It might help the accountants

**Comment by AbhayAysola** [comment]
> @AbhayAysola yep you'll get paid. Can you post your account number on the `issue` too? It might help the accountants

Sure, will do that. Thanks :)

**Pull request merged**
