### PR TITLE
Top nav changes

### PR DESCRIPTION
**Pull request by amarjeet987**
Navbar updates as per the new UI

### CODE REVIEW

**Comment by amarjeet987** [comment]
Ignore the old commits, I pulled them from upstream but forgot to push to my origin master branch and made a new branch before that, maybe that's why. 🤥

**Comment by buckyroberts** [comment]
Sticking "DON'T MERGE" label on it until the BE is done and we can test the auth flow.

**Comment by amarjeet987** [comment]
Yeah cool, makes sense. 🐱‍🏍

**Comment by amarjeet987** [comment]
> Sticking "DON'T MERGE" label on it until the BE is done and we can test the auth flow.

"BE"? 🤔

**Comment by AbhayAysola** [comment]
> > Sticking "DON'T MERGE" label on it until the BE is done and we can test the auth flow.
> 
> "BE"? 🤔

I'm guessing backend

**Comment by amarjeet987** [comment]
lmao probably yes. I thought some other functionality just in case, nvm xD

**Pull request merged**
