### PR TITLE
Update Swedish hello world

### PR DESCRIPTION
**Pull request by AntonFredrikSvensson**
#351 
Update Swedish hello world
Account: c636813810492c91fc4fd3d64b8effc2c3f3abc0e790e7d945cc4577e9e410d7

### CODE REVIEW

**Comment by shahraizali** [comment]
ISO Correct ✅
Spellings Correct ✅
Approved

**Comment by AntonFredrikSvensson** [comment]
@angle943 Hi Justin!

**Comment by AntonFredrikSvensson** [comment]
@angle943 
Am I to going to receive a payment for the commit or how does it work?

**Comment by AntonFredrikSvensson** [comment]
@shahraizali Hi Ali! I never received any payment for this commit. As you can see I already tried to contact Justin, but didn't receive any reply. Can you help me get this sorted?

**Comment by shahraizali** [comment]
okay, I have forwarded it to the payments. sorry about the delay. Justin is away for a while probably that's why he missed it.

**Comment by AntonFredrikSvensson** [comment]
@shahraizali Thanks a lot Ali! No problem. No I have received the payment.

**Pull request merged**
