### PR TITLE
Fixes: #564 Left task menu Issue

### PR DESCRIPTION
**Pull request by manishram**
fixes: #564 

Screenshot:
tnb

Account:
0f92e975101eb96cea80dce430d74efd3172fa229377818d467ded85dcf2ab6c

### CODE REVIEW

**Comment by manishram** [comment]
@thesanjeevsharma please review the PR. Thanks

**Comment by Hristijan95** [comment]
Hello @manishram , thank you for contributing. Please do not tag the team member on every PR, we are getting trough the PRs ass fast as we can.
I would suggest some changes to your solution before we merge this PR, as the current solution will not work if for example in the future we have another repository with longer name that does not contain the word thenewboston.
My suggestion would be to edit the REPOSITORIES list in `src/components/FlatNavLinks/index.tsx` to be a json object instead of a string, for example:

`{title: 'Account-Manager', url: Repository.accountManager},`

This way we can always choose a different name, not depending on the URL and then in `src/components/FlatNavLinks/index.tsx` you can use `option.title` to to show the title and `option.url` for the rest.

**Comment by manishram** [comment]
Yeah sure.

**Review by accessdeniedIT — APPROVED** [review]
ignore this approve, some changes request by Hristijan93

**Comment by manishram** [comment]
Actually, Hristijan95 told me to go with another approach that he described above which seems to be more accurate.

**Comment by accessdeniedIT** [comment]
Ok, @ me when you submit the changes.

**Comment by manishram** [comment]
Getting some errors. I'll push changes one done.

**Comment by accessdeniedIT** [comment]
Prettier Error?

**Comment by manishram** [comment]
@accessdeniedIT Not with Prettier. But actual code maybe I am doing something wrong.

**Comment by manishram** [comment]
Not ready yet. Need to fix Teams as well.

**Comment by manishram** [comment]
Ready for review.

**Pull request closed without merging**
