### PR TITLE
Add Serbian language

### PR DESCRIPTION
**Pull request by nberic**
Added "Hello World" text in Serbian language.

### CODE REVIEW

**Comment by Hristijan95** [comment]
@odetolataiwo @Rajputusman , 500.

**Comment by Rajputusman** [comment]
@nberic What is your account no # ?

**Comment by nberic** [comment]
@Rajputusman What do you mean by account number? My GitHub account number or account number in the peer network?

**Comment by Rajputusman** [comment]
@nberic In TNB what is your account No? So I can send coins to you as reward

**Comment by nberic** [comment]
@Rajputusman Excuse me for long reply time. I was trying to find the account ID for TNB social network.
Long story short, my account id is `dc874f3df2f4ef76d4029303ae4b42804afe5a54275e732de0226a4a794a67e6`.

**Pull request merged**
