### PR TITLE
fix the "Join community" Header and icon centering

### PR DESCRIPTION
**Pull request by T-Whiz**
---------------------------------------------------------------------------------------------------------------------------------------
I think I got it this time... Took a doc and a video but I think I understand the whole PR process. Let me know if this works for you guys. Thanks for your patience :)

For the heading text you need to add a text-align: center; to the css. ( Doesn't break desktop )

BEFORE:
headerfixbefore

AFTER:
headerfix

---------------------------------------------------------------------------------------------------------------------------------------
To fix the icons you just need to fix the margin

BEFORE:
iconsfixbefore

AFTER:
iconsfix

Account number : f8f1aa375cf55a8c83fe3bfd01baf74e928e2bb1e6f8b4775a6cd8de1fdcb134

### CODE REVIEW

**Comment by Hristijan95** [comment]
@T-Whiz , good job, now the PR is okay, however there are still some issues with the cards on certain screen sizes:
Screen Shot 2020-11-10 at 23 31 44

Just resize the browser and you'll notice it, it's right before the cards fall in a new row.

**Comment by Hristijan95** [comment]
Fixed in #716

**Comment by T-Whiz** [comment]
Sorry I forgot to change the margin: 10px auto to 
margin: 10px 10px. 

Was this already fixed or do you want me to make a pr ?

**Comment by Hristijan95** [comment]
@T-Whiz , sure thing. Unfortunately this issue was already fixed by someone else in the meantime, so I had to close this issue. Feel free to pick some of the other issues if you want to continue contributing.

**Pull request closed without merging**
