### PR TITLE
Bug/#645 team lead text alignment issue

### LINKED ISSUE #645: Team Lead tag's text is misaligned
**Bug Description**
Team Lead tag's text is misaligned.

**Steps to Reproduce**
1. Go to: [Teams](https://thenewboston.com/teams)

**Expected behavior**
It should be vertically and horizontally  center aligned.

**Screenshots/Recordings**
image

**OS and Browser**
 - OS: Android, iOS
 - Browser: Firefox, Safari

**Additional context**
Solution: 
flex it, align and justify center

### PR DESCRIPTION
**Pull request by whitelionx**
Resolves #645 

Account number: fb84a32a698a03dd327c4ce673f19fa0acf6e68cb50f143d5d7c080471bc4625

image

### CODE REVIEW

**Comment by whitelionx** [comment]
@Hristijan95 is the task done successfully or? :D

**Comment by Hristijan95** [comment]
@whitelionx yes, thanks for contributing. You will receive your coins when this issue gets picked up by the Head of Contributor Payments. (It shouldn't take too much time from now)

**Comment by whitelionx** [comment]
@Hristijan95 what I am also keen to know, how could I become a part of the team :D

**Comment by Hristijan95** [comment]
@whitelionx , join the [community slack](https://thenewboston.com/social), explore the docs and if you feel that you can contribute more and feel confident with your knowledge, apply for some of the [positions listed here](https://thenewboston.com/openings/All).
If you have any more question, you can post them on slack.

**Pull request merged**
