### PR TITLE
Add Hello World in Xhosa.

### PR DESCRIPTION
**Pull request by Gourob-Dev**

### CODE REVIEW

**Comment by Hristijan95** [comment]
@odetolataiwo @Rajputusman , 500.

**Comment by Rajputusman** [comment]
@Gourob-Dev  What is your account no# for TNB?

**Comment by Gourob-Dev** [comment]
Sorry, I don't currently have a PC but I have access to an android phone. Can I create an account there?

**Comment by Rajputusman** [comment]
It is currently not available for android. @Gourob-Dev

**Pull request merged**
