### PR TITLE
Add github action workflow for linting

### LINKED ISSUE #1032: [Suggestion] Automate testing/linting using github actions
Currently, the repository has certain code styles to obey, such as code styles for javascript, typescript by `eslint`.

Code reviewers would have to manually look through PR code styles and request changes if the PR changes does not fully obey the code styles.

Suggestion: use github actions to automate the linting or any testings that may be constructed in the future.

Advantages:
- Saves effort from code reviewers on code styles
- Serves as a reminder for contributors obey the code styles, since the github status checks will fail in the PR if not obeyed

Am happy to work on this if this is needed.

### PR DESCRIPTION
**Pull request by jamessspanggg**
Fixes #1032 

I tested this in my forked website repo, and here's a PR with the workflow in action: https://github.com/jamessspanggg/Website-1/pull/2

Acc No: c54c04774efaae20746fd3f29cdd619fea512e119bc1082b863572b2e8844104

### CODE REVIEW

**Comment by lapstjup** [comment]
@jamessspanggg Can we have a failure scenario for this available as a PR ?

**Comment by jamessspanggg** [comment]
@lapstjup can check from the [PR](https://github.com/jamessspanggg/Website-1/pull/2) for the failure scenario

**Comment by lapstjup** [comment]
@jamessspanggg Cool stuff man :D.

Few doubts here since I am not well equipped with its knowledge :-
- What happens when the code is directly pushed to master or development (which can only be done by core team ) ? This action will run in the terminal itself and fail for linting errors ?
- Also what if a person uses Github GUI to commit directly to remote master/development ?

**Comment by jamessspanggg** [comment]
> Few doubts here since I am not well equipped with its knowledge :-
> 
> * What happens when the code is directly pushed to master or development (which can only be done by core team ) ? This action will run in the terminal itself and fail for linting errors ?

If you are directly pushing it to the team's master or development branch, the checks will still occur on Github. Note that the checks run after you have pushed to the branch, so it won't prevent you if it fails. But however, it will show the status of each commit. i.e. the green tick or a red cross in the commit as shown below, clicking on the tick/cross will show you more details on the checks:
Screen Shot 2020-11-26 at 7 53 22 PM


> * Also what if a person uses Github GUI to commit directly to remote master/development ?

Committing directly using github's gui will have the same effect as I have described above, have tested it in my own master branch. (Don't worry I will rebase and force push it)
Screen Shot 2020-11-26 at 8 04 34 PM

**Review by thesanjeevsharma — APPROVED** [review]

**Pull request merged**
