### PR TITLE
its not going away HELP

### PR DESCRIPTION
**Pull request by hasham56**
idk how to remove this pull request completely :3 its always in my compare field @manishram

### CODE REVIEW

**Comment by lapstjup** [comment]
@hasham56 Do you want me to close this PR ?

**Comment by hasham56** [comment]
@lapstjup no sir... I can close it myself.. But even after deleting this branch i cannot request for a new pull request... I keep getting these changes in my compare and pull section :(

**Comment by manishram** [comment]
Hey @hasham56 make new branch of "development" bramch then make changes to it. I am not sure but maybe you are making sub-branch of the branch(new-contributor) you have already created. That's why your changes get cloned to the new sub branch.

**Comment by hasham56** [comment]
@manishram i think its because someone made changes to my request... I have tried what u said almost 5 times in different ways

**Comment by lapstjup** [comment]
@hasham56 You can take the latest pull from **thenewboston-developers:development** to your fork **hasham56:development** . And then I would recommend you creating a new branch like **fix-bla-bla-issue** from **hasham56:development** to address any issue. 

If it's getting too confusing, delete your current fork and create a new one.

**Comment by hasham56** [comment]
@lapstjup thanks will try that ❤️

**Comment by manishram** [comment]
Yes sanjeev made a little chang to your PR by providing `contributorId`, some value which you did set to `null` previously. And as your PR got merged, you can see your changes.

**Comment by manishram** [comment]
> @hasham56 You can take the latest pull from **thenewboston-developers:development** to your fork **hasham56:development** . And then I would recommend you creating a new branch like **fix-bla-bla-issue** from **hasham56:development** to address any issue.
> 
> If it's getting too confusing, delete your current fork and create a new one.

Yes this always helps.

**Pull request closed without merging**
