### PR TITLE
Help page bug

### PR DESCRIPTION
**Pull request by GermaVinsmoke**
Solves issue https://github.com/thenewboston-developers/Website/issues/305
The problem was with the `align-items` property.

### CODE REVIEW

**Review by angle943 — APPROVED** [review]

**Comment by buckyroberts** [comment]
@GermaVinsmoke Do you have an account number where we can send your coins to? Every accepted PR gets paid.

**Comment by GermaVinsmoke** [comment]
I think my account number is this 8ff54e36f7fc534230faa1420c0116b2805abc4d8edb6a3661905ea0b4c875bd
What can we do with these points btw?

**Comment by angle943** [comment]
@GermaVinsmoke think of it as cryptocurrency. Doesn't have too much value now, but it will increase as we increase in usage

**Comment by GermaVinsmoke** [comment]
@angle943 This one is also not paid.

**Pull request merged**
