### PR TITLE
Added Hello World in Ewe Language

### PR DESCRIPTION
**Pull request by successcard**
Account # 14be9505e28bdbd872cc6038c990e93cf02066fa922bb08ba97974fa951e9e22

### CODE REVIEW

**Review by angle943 — CHANGES_REQUESTED** [review]
1. according to https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes , the language code for Ewe language is `ee`

2. Can you provide a link to a translator that will verify what you have translated is correct?

3. Is there supposed to be an extra space at the end?

**Comment by angle943** [comment]
@successcard do you have a link I can verify your translation against?

**Comment by successcard** [comment]
> @successcard do you have a link I can verify your translation against?

Please you can use this link to verify: https://glosbe.com/en/ee

**Comment by successcard** [comment]
@angle943 Just wondering if I would get the coins credited to my account for the translation.

**Comment by angle943** [comment]
yes @successcard one of our accountants should pay you when he does the next round of payments. If you haven't received payments in the next 7 days, please let me know here

**Comment by successcard** [comment]
> yes @successcard one of our accountants should pay you when he does the next round of payments. If you haven't received payments in the next 7 days, please let me know here

@angle943 Please I haven't received the payment yet. Just wanted to let you know.

**Comment by angle943** [comment]
@successcard sorry about that. I've reached out to them, you should be getting payment soon

**Comment by successcard** [comment]
> @successcard sorry about that. I've reached out to them, you should be getting payment soon

Thank you @angle943

**Pull request merged**
