### PR TITLE
Added "Saluton mondo" in Esperanto  language

### PR DESCRIPTION
**Pull request by gatvay23924**
Added Esperanto language
Language - Esperanto 
ISO 639-1 =eo
Account number: 5d5542b8749534b1c6b51ab7819382ce773439bb5aacdc93ad0b79ae4ff9f613

### CODE REVIEW

**Comment by lapstjup** [comment]
@gatvay23924 - We want the w in **World** in caps so I guess m will be capital in **mondo** ?

**Comment by melsh123221** [comment]
hello world=Saluton mondo

Hello World=Saluton mondo

**Comment by melsh123221** [comment]
both are same

**Comment by gatvay23924** [comment]
as
f

**Review by amarjeet987 — CHANGES_REQUESTED** [review]
The english translation is "Hello World" ( with capital H and W ), so we're trying to keep it consistent for the rest of the languages as well. "Saluton mondo" translates to "Hello world", like mentioned above.

**Pull request closed without merging**
