### PR TITLE
Convert Modal,Navigation to styled-components

### PR DESCRIPTION
**Pull request by lokeshn011101**
This PR converts Modal and Navigation styles into styled-components in reference to #2081.
6 files were changes and the existing SCSS files were deleted.
Before Changing:

https://user-images.githubusercontent.com/63955341/137081263-32c6a3d4-a7a1-4a85-95ac-cf0a4f191019.mp4

https://user-images.githubusercontent.com/63955341/137081371-2e83d272-1d52-4905-b1be-c59bbaece31e.mp4

After Changing:

https://user-images.githubusercontent.com/63955341/137081433-98193004-5278-47a2-91bc-0b6de336164f.mp4

https://user-images.githubusercontent.com/63955341/137081461-ce1c400e-0c61-4ee5-ab88-fe6f8af5ea8b.mp4

I couldn't find where Modal and Navigation components are used. So I added them in the Teams container for testing and removed them while committing.

### CODE REVIEW

**Comment by lokeshn011101** [comment]
Damn those are some silly things that I missed. Thanks for reviewing the PR. I'll do the necessary changes!

**Comment by lokeshn011101** [comment]
@jamessspanggg Can you please review the PR once again?

**Comment by lokeshn011101** [comment]
@jamessspanggg Will this PR get merged?

**Comment by jamessspanggg** [comment]
@lokeshn011101 yep sorry I have work during the day so I can only review at night

**Pull request merged**
