### PR TITLE
Enforce width of task sections in leaderboard

### LINKED ISSUE #839: [Leaderboard] Inconsistencies in width of tasks
**Bug Description**
When there is a  repository name that is long, i.e. `thenewboston-python-client`, the long repository name takes up more width and pushes the user section more towards the left.

**Steps to Reproduce**
1. Go to leaderboard
2. Click on 30d filter
3. Observe the difference between first and second contributor

**Expected behavior**
Widths of each section should be standardised.

**Actual behavior**
Some contributor's repository section takes up more space than the others.

**Screenshots/Recordings**
Screen Shot 2020-11-15 at 5 43 14 PM

Note that when the task name is too short, the repository section will be shifted left.
Screen Shot 2020-11-15 at 5 43 46 PM

**OS and Browser**
 - OS: Mac, Chrome, Safari

**Additional context**
Enforcing the widths of each section should solve the issue.

**Account Number**
c54c04774efaae20746fd3f29cdd619fea512e119bc1082b863572b2e8844104

### PR DESCRIPTION
**Pull request by jamessspanggg**
Fixes #839 

After enforcing the widths, added hover title:
- Long repository name:
Screen Shot 2020-11-15 at 5 53 48 PM

- Short task name:
Screen Shot 2020-11-15 at 5 53 26 PM

- The width of the amount is set to be able to accommodate up to millions.
Screen Shot 2020-11-15 at 5 57 17 PM

Account Number:
c54c04774efaae20746fd3f29cdd619fea512e119bc1082b863572b2e8844104

### CODE REVIEW

**Comment by lapstjup** [comment]
@jamessspanggg I think the task title was already taken care by #815.

**Review by thesanjeevsharma — APPROVED** [review]

**Comment by jamessspanggg** [comment]
> @jamessspanggg I think the task title was already taken care by #815. 

Yep this is for the repository title.

**Comment by thesanjeevsharma** [comment]
@lapstjup both issues are different!

**Comment by lapstjup** [comment]
Ahh just got it. This is for repository.

**Pull request merged**
