### PR TITLE
Clean and Crawl in the doc

### PR DESCRIPTION
**Pull request by VincentHch**

### CODE REVIEW

**Comment by VincentHch** [comment]
This pull request may be incomplete. I'm still reading the repo to understand these endpoints but it could be great to have a  first overview !

**Comment by VincentHch** [comment]
#924

**Comment by VincentHch** [comment]
image
image

I uploaded the file so that you don't need to download and run for this PR

**Comment by VincentHch** [comment]
@charnysh-dev

**Review by vosi — APPROVED** [review]

**Review by niaztv — APPROVED** [review]

**Pull request merged**
